version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_HOST: db
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
