version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-postgres}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-schedule}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-secret}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    env_file: ./.env
    environment:
      APP_HOST: ${APP_HOST:-app}
      APP_PORT: ${APP_PORT:-8080}
      SERVER_NAME: ${SERVER_NAME:-localhost}
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/www:/var/www/certbot:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx_status"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
