version: "3.9"
services:
  db:
    # Fresh PostgreSQL instance
    image: postgres:16.2-alpine
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-schedule}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
