version: '3.8'
services:
  db:
    # Fresh PostgreSQL instance
    image: postgres:16.2
    environment:
      POSTGRES_DB: schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_HOST: db
    restart: unless-stopped
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    restart: unless-stopped
    environment:
      APP_HOST: app
      APP_PORT: 8080
    entrypoint: >
      /bin/sh -c "
        envsubst '\$${APP_HOST} \$${APP_PORT}' \
          < /etc/nginx/templates/nginx.conf.template \
          > /etc/nginx/conf.d/default.conf &&
        exec nginx -g 'daemon off;'
      "
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    depends_on:
      - nginx
    command:
      - --nginx.scrape-uri=http://nginx/nginx_status
    ports:
      - "9114:9113"
