ALTER TABLE lessons
  ALTER COLUMN date_time TYPE TIMESTAMPTZ USING date_time AT TIME ZONE 'UTC',
  ALTER COLUMN date_time SET NOT NULL;
ALTER TABLE time_slots
  ALTER COLUMN start TYPE TIMESTAMPTZ USING start AT TIME ZONE 'UTC',
  ALTER COLUMN start SET NOT NULL;
ALTER TABLE time_slots
  ALTER COLUMN end_time TYPE TIMESTAMPTZ USING end_time AT TIME ZONE 'UTC',
  ALTER COLUMN end_time SET NOT NULL;
