ALTER TABLE lessons
  ALTER COLUMN date_time TYPE TIMESTAMPTZ NOT NULL USING date_time AT TIME ZONE 'UTC';
ALTER TABLE time_slots
  ALTER COLUMN start TYPE TIMESTAMPTZ NOT NULL USING start AT TIME ZONE 'UTC';
ALTER TABLE time_slots
  ALTER COLUMN end_time TYPE TIMESTAMPTZ NOT NULL USING end_time AT TIME ZONE 'UTC';
