CREATE TABLE IF NOT EXISTS notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL REFERENCES lessons(id),
    channel VARCHAR(20) NOT NULL,
    sent_at TIMESTAMPTZ,
    status VARCHAR(20),
    read_at TIMESTAMPTZ,
    payload_json TEXT
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    action VARCHAR(20) NOT NULL,
    old_json TEXT,
    new_json TEXT,
    actor_id BIGINT,
    ts TIMESTAMPTZ DEFAULT now()
);
