{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "schedule-app.fullname" . }}-backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "schedule-app.serviceAccountName" . }}
          automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["/backup-db.sh"]
              envFrom:
                - configMapRef:
                    name: {{ include "schedule-app.fullname" . }}-backend
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "schedule-app.fullname" . }}
                      key: postgres-password
                - name: BACKUP_DIR
                  value: /backups
              resources:
                {{- toYaml .Values.backup.resources | nindent 16 }}
              volumeMounts:
                - name: backup
                  mountPath: /backups
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: {{ include "schedule-app.fullname" . }}-backup
{{- end }}
