apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-app.fullname" . }}-backend
  labels:
    {{- include "schedule-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "schedule-app.fullname" . }}-backend

