{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-app.fullname" . }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "schedule-app.fullname" . }}-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
{{- end }}
