{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-app.fullname" . }}-frontend
  labels:
    {{- include "schedule-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "schedule-app.fullname" . }}-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
{{- end }}
