{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "schedule-app.fullname" . }}-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "schedule-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        {{- include "schedule-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      serviceAccountName: {{ include "schedule-app.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.migrations.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/wait-for-db.sh", "java", "-jar", "/app/app.jar", "--spring.main.web-application-type=none"]
          envFrom:
            - configMapRef:
                name: {{ include "schedule-app.fullname" . }}-backend
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "schedule-app.fullname" . }}
                  key: postgres-password
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
{{- end }}
