apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-app.fullname" . }}-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "schedule-app.fullname" . }}-postgresql

