{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-app.fullname" . }}-postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    app: {{ include "schedule-app.fullname" . }}-postgresql
{{- end }}

