apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-app.fullname" . }}-rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: {{ include "schedule-app.fullname" . }}-rabbitmq
