{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-app.fullname" . }}-rabbitmq
spec:
  ports:
    - port: {{ .Values.rabbitmq.port }}
      targetPort: {{ .Values.rabbitmq.port }}
  selector:
    app: {{ include "schedule-app.fullname" . }}-rabbitmq
{{- end }}
