spring:
  profiles:
    default: postgres
  mvc:
    pathmatch:
      # Use legacy Ant path matcher for complex patterns in SpaController
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: ${SMTP_AUTH}
      mail.smtp.starttls.enable: ${SMTP_STARTTLS}

app:
  mail:
    from: ${MAIL_FROM}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}

jwt:
  # Use a secure random key in production. Fallback string is suitable for local
  # development but won't work if trimmed below 32 bytes.
  secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef}

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
