spring:
  profiles:
    default: h2
  jpa:
    open-in-view: false

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}

jwt:
  secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
