spring:
  profiles:
    default: h2
    group:
      dev: h2
  jpa:
    open-in-view: false
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: ${SMTP_AUTH}
      mail.smtp.starttls.enable: ${SMTP_STARTTLS}

app:
  mail:
    from: ${MAIL_FROM}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}

jwt:
  secret: ${JWT_SECRET}

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
