global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'schedule-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
