image:
  repository: ghcr.io/idzumikatsu/trash/backend
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []

replicaCount: 1

frontend:
  image: ghcr.io/idzumikatsu/trash/frontend
  tag: latest
  pullPolicy: IfNotPresent
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

startupProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 30

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false

serviceAccount:
  create: true
  name: ""
  automount: false

nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: schedule.local
  tls: []

# Deploy an internal PostgreSQL instance alongside the application
postgresql:
  enabled: true
  host: postgresql
  port: 5432
  image: postgres:16.2-alpine
  persistence:
    enabled: true
    size: 1Gi
  database: schedule
  username: postgres
  password: postgres
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

jwtSecret: secret

rabbitmq:
  enabled: true
  host: rabbitmq
  port: 5672
  image: rabbitmq:3.13-management
  username: user
  password: password
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

serviceMonitor:
  enabled: false

pdb:
  enabled: true
  minAvailable: 1

migrations:
  enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  backup:
    enabled: false
    schedule: "0 3 * * *"
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

networkPolicy:
  enabled: true

# Settings for database backups
backup:
  enabled: false
  persistence:
    enabled: false
