image:
  repository: schedule-backend
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: schedule.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

postgresql:
  image: postgres:16.2-alpine
  persistence:
    enabled: true
    size: 1Gi
  database: schedule
  username: postgres
  password: postgres

jwtSecret: secret

rabbitmq:
  image: rabbitmq:3.13-management
  username: user
  password: password
  persistence:
    enabled: true
    size: 1Gi
