image:
  repository: schedule-backend
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: schedule.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

postgresql:
  enabled: true
  host: postgresql
  port: 5432
  image: postgres:16.2-alpine
  persistence:
    enabled: true
    size: 1Gi
  database: schedule
  username: postgres
  password: postgres
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

jwtSecret: secret

rabbitmq:
  enabled: true
  host: rabbitmq
  port: 5672
  image: rabbitmq:3.13-management
  username: user
  password: password
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

serviceMonitor:
  enabled: true

pdb:
  enabled: true
  minAvailable: 1

migrations:
  enabled: true

backup:
  enabled: false
  schedule: "0 3 * * *"
  persistence:
    enabled: true
    size: 1Gi
