image:
  repository: schedule-backend
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: schedule.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

postgresql:
  enabled: true
  host: postgresql
  port: 5432
  image: postgres:16.2-alpine
  persistence:
    enabled: true
    size: 1Gi
  database: schedule
  username: postgres
  password: postgres

jwtSecret: secret

rabbitmq:
  enabled: true
  host: rabbitmq
  port: 5672
  image: rabbitmq:3.13-management
  username: user
  password: password
  persistence:
    enabled: true
    size: 1Gi

serviceMonitor:
  enabled: true

pdb:
  enabled: true
  minAvailable: 1
