# Глобальные настройки
global:
  imagePullSecrets: []

image:
  repository: ghcr.io/idzumikatsu/trash/backend
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []

replicaCount: 3

frontend:
  image: ghcr.io/idzumikatsu/trash/frontend
  tag: latest
  pullPolicy: IfNotPresent
  enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

startupProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 30

resources:
  requests:
    memory: "512Mi"
    cpu: "1"
  limits:
    memory: "1Gi"
    cpu: "2"

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false

serviceAccount:
  create: true
  name: ""
  automount: false

nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: schedule.example.com
  tls:
    - secretName: schedule-tls
      hosts:
        - schedule.example.com

# Deploy an internal PostgreSQL instance alongside the application
postgresql:
  enabled: true
  fullnameOverride: "postgresql"
  auth:
    postgresPassword: "YourSecurePassword123"
  host: postgresql
  port: 5432
  image:
    repository: postgres
    tag: 16.2-alpine
    pullPolicy: IfNotPresent
    pullSecrets: []
  metrics:
    image:
      pullSecrets: []
  volumePermissions:
    image:
      pullSecrets: []
  persistence:
    enabled: true
    size: 10Gi
  database: schedule
  username: postgres
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

jwtSecret: CHANGEME

rabbitmq:
  enabled: true
  host: rabbitmq
  port: 5672
  image: rabbitmq:3.13-management
  username: user
  password: password
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

serviceMonitor:
  enabled: false

pdb:
  enabled: true
  minAvailable: 1

migrations:
  enabled: true
  imagePullSecrets:
    - name: ghcr-secret
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"

  backup:
    enabled: false
    schedule: "0 3 * * *"
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"

networkPolicy:
  enabled: true

# Settings for database backups
backup:
  enabled: false
