name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROXY_HOST: ${{ secrets.PROXY_HOST }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}
    steps:
      - name: Configure proxy variables
        run: |
          # Only export proxy environment variables when both PROXY_HOST and
          # PROXY_PORT are provided. When either is missing we simply skip
          # proxy setup so the job continues without failing.
          if [ -n "$PROXY_HOST" ] && [ -n "$PROXY_PORT" ]; then
            echo "http_proxy=http://$PROXY_HOST:$PROXY_PORT" >> "$GITHUB_ENV"
            echo "https_proxy=http://$PROXY_HOST:$PROXY_PORT" >> "$GITHUB_ENV"
            echo "HTTP_PROXY=http://$PROXY_HOST:$PROXY_PORT" >> "$GITHUB_ENV"
            echo "HTTPS_PROXY=http://$PROXY_HOST:$PROXY_PORT" >> "$GITHUB_ENV"
            echo "PROXY_HOST=$PROXY_HOST" >> "$GITHUB_ENV"
            echo "PROXY_PORT=$PROXY_PORT" >> "$GITHUB_ENV"
          else
            echo "Proxy variables not set, skipping proxy configuration"
          fi

      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure git proxy
        if: env.PROXY_HOST && env.PROXY_PORT
        run: |
          git config --global http.proxy $HTTP_PROXY
          git config --global https.proxy $HTTPS_PROXY

      - name: Generate Maven settings
        if: env.PROXY_HOST && env.PROXY_PORT
        run: envsubst < .mvn/settings.xml.in > .mvn/settings.xml

      - name: Build and test with Maven
        run: |
          if [ -n "$PROXY_HOST" ] && [ -n "$PROXY_PORT" ]; then
            export MAVEN_OPTS="-Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT -Dhttps.proxyHost=$PROXY_HOST -Dhttps.proxyPort=$PROXY_PORT"
          fi
          ./mvnw -s .mvn/settings.xml -B verify

      - name: Deploy
        run: echo "Deployment not yet configured"
