name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies and build
        run: |
          npm ci
          npm run build
        working-directory: frontend

      - name: Build backend JAR
        run: ./gradlew bootJar
        working-directory: backend

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "backend/build/libs/*.jar"
          target: "/opt/schedule-app"
          strip_components: 3

      - name: Install systemd unit
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "infra/systemd/schedule-app.service"
          target: "/etc/systemd/system"
          strip_components: 2
          overwrite: true


      - name: Restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo mv /opt/schedule-app/*.jar /opt/schedule-app/app.jar
            sudo systemctl daemon-reload
            sudo systemctl enable schedule-app
            sudo systemctl restart schedule-app
