# .github/workflows/deploy-vps.yml
name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up runtimes
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Build frontend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Lint frontend
        run: npm run lint
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      # Copy frontend build into backend static
      - name: Copy frontend build into backend static
        run: |
          mkdir -p backend/src/main/resources/static
          rm -rf backend/src/main/resources/static/*
          cp -r frontend/dist/* backend/src/main/resources/static/

      # 4. Build & test backend
      - name: Run backend tests
        run: ./gradlew test
        working-directory: backend

      - name: Build backend JAR
        run: ./gradlew bootJar
        working-directory: backend

      # 5. Archive artifact for debugging (optional)
      - name: Archive backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: schedule-app-jar
          path: backend/build/libs/*.jar

      # 6. Deploy to VPS: cleanup & prerequisites
      - name: Clean old app on VPS & check Java
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo rm -rf /opt/schedule-app/*
            if ! java -version 2>&1 | grep '21'; then
              echo 'ERROR: Java 21 not found on VPS'
              exit 1
            fi

      # 7. Copy new JAR
      - name: Deploy JAR to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "backend/build/libs/*.jar"
          target: "/opt/schedule-app"
          strip_components: 3
          overwrite: true

      # 7.1 Rename JAR to app.jar on VPS
      - name: Rename JAR to app.jar on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo mv /opt/schedule-app/*.jar /opt/schedule-app/app.jar
            sudo chown root:root /opt/schedule-app/app.jar
            sudo chmod 644 /opt/schedule-app/app.jar

      # 8. Copy systemd unit file
      - name: Upload systemd unit
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "infra/systemd/schedule-app.service"
          target: "/etc/systemd/system"
          strip_components: 2
          overwrite: true

      # 9. Configure environment variables on VPS
      - name: Configure environment file on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo tee /etc/schedule-app.env > /dev/null <<EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            # Добавьте другие переменные по необходимости
            EOF
            sudo chown root:root /etc/schedule-app.env
            sudo chmod 640 /etc/schedule-app.env

      # 10. Restart the service
      - name: Restart schedule-app service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl enable schedule-app
            sudo systemctl restart schedule-app
