name: Smokescreen Nginx Build

on:
  push:
    paths:
      - 'infra/nginx/**'
      - '.github/workflows/nginx-smoke-test.yml'

jobs:
  build-and-test-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Nginx image
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            -t schedule-app-nginx-test \
            infra/nginx
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Test generated Nginx config
        run: |
          docker run --rm schedule-app-nginx-test nginx -t

      - name: Smoke-start container & curl
        run: |
          docker run -d --name smoke-nginx -p 8081:80 schedule-app-nginx-test
          sleep 3
          curl -f http://localhost:8081 || (docker logs smoke-nginx && exit 1)
        
      - run: docker rm -f smoke-nginx
